"""Kings Research cross-domain offerings portfolio, encoded so the brain can reason over it.

Each pillar has:
  - services: the exact service names from the portfolio, each with keywords, the job functions
    it suits and the trigger types it answers
  - pitch: the plain-language outcome the pillar delivers
  - assets: small, genuinely producible things to offer in Email 2
  - fit rules: B2C-only pillars and the minimum company scale that makes the pitch credible
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Service:
    name: str
    keywords: tuple[str, ...] = ()
    functions: tuple[str, ...] = ()
    triggers: tuple[str, ...] = ()


@dataclass(frozen=True)
class Pillar:
    id: str
    name: str
    purpose: str
    pitch: str
    assets: tuple[str, ...]
    services: tuple[Service, ...]
    b2c_only: bool = False
    min_scale: str = "small"  # small | mid | large
    prior: float = 0.0  # small base-rate bonus for broadly applicable pillars
    extra: dict = field(default_factory=dict)


def S(name: str, kw: str = "", fn: str = "", tr: str = "") -> Service:
    return Service(
        name=name,
        keywords=tuple(k.strip().lower() for k in kw.split("|") if k.strip()),
        functions=tuple(fn.split()),
        triggers=tuple(tr.split()),
    )


PILLARS: tuple[Pillar, ...] = (
    Pillar(
        id="market_intel",
        name="Market & Industry Intelligence",
        purpose="Help clients understand where a market is heading and what it means for their business.",
        pitch="a clear, sourced view of where their market is heading: size, growth, drivers and what it means for their plans",
        assets=("a one-page outline of how we would size and forecast their specific segment",
                "a short list of the market questions we would answer for their planning cycle"),
        prior=0.08,
        services=(
            S("Market Size & Forecasting", "market size|forecast|growth|demand|revenue|billion|million", "strategy finance executive investment research_insights", "funding financial_results expansion_geo"),
            S("TAM / SAM / SOM Assessment", "tam|addressable|serviceable|obtainable|investor|board|pitch|funding|series", "executive finance strategy investment", "funding"),
            S("Market Growth & Outlook", "outlook|growth|slowdown|recovery|guidance|2027|next year", "executive strategy finance", "financial_results restructuring"),
            S("Market Trends & Emerging Themes", "trend|emerging|shift|demand|consumer|adoption", "marketing strategy product research_insights", "technology sustainability"),
            S("Market Dynamics Assessment: Drivers, Restraints, Trends, & Opportunities", "drivers|restraints|headwinds|tailwinds|pressure|volatility", "strategy executive", "financial_results restructuring"),
            S("Industry Structure & Value Chain Analysis", "value chain|vertical integration|margin|middlemen|structure|downstream|upstream", "strategy executive investment", "m_and_a partnership"),
            S("Regional / Country Opportunity Assessment", "country|region|international|expansion|enter|europe|asia|middle east|africa|latin america|india|gcc", "executive strategy sales", "expansion_geo"),
            S("Market Maturity Assessment", "maturity|saturated|mature|commoditi", "strategy product", "financial_results"),
            S("Regulatory & Policy Landscape", "regulation|regulatory|policy|compliance|law|directive|approval|ban|mandate|fda|epa|eu ", "legal_compliance executive strategy product", "regulation tariff_trade"),
            S("Technology & Innovation Landscape", "technology|innovation|ai|digital|automation", "technology product strategy", "technology"),
            S("Disruption & Market Evolution Tracking", "disrupt|new entrant|evolution|shake-up|consolidation", "strategy executive research_insights", "technology m_and_a"),
            S("Scenario-Based Market Outlook", "scenario|uncertain|tariff|election|volatility|downturn|recession", "executive strategy finance", "tariff_trade regulation restructuring"),
        ),
    ),
    Pillar(
        id="competitive_intel",
        name="Competitive Intelligence",
        purpose="Help clients understand competitors and identify opportunities to differentiate.",
        pitch="an evidence-based picture of what competitors are doing, where they are strong and weak, and where to differentiate",
        assets=("a sample benchmarking grid showing the competitor dimensions we would compare",
                "a sample competitive battlecard layout for their category"),
        prior=0.08,
        services=(
            S("Competitive Landscape Mapping", "competitor|competition|rival|landscape|players", "strategy executive marketing", "leadership m_and_a"),
            S("Competitor Profiling", "competitor|rival|profile", "strategy marketing sales research_insights", ""),
            S("Market Share Analysis", "market share|share|leader|position|rank", "executive strategy marketing finance", "financial_results"),
            S("Product / Service Portfolio Benchmarking", "portfolio|product line|range|offering|launch", "product marketing", "product_launch"),
            S("Pricing Benchmarking", "price|pricing|discount|cost", "sales marketing finance product", "pricing"),
            S("Business Model Benchmarking", "business model|subscription|as-a-service|platform|recurring", "strategy executive", "pricing technology"),
            S("Technology & Capability Benchmarking", "capability|technology|ai|automation|platform", "technology product", "technology"),
            S("Competitor Strategy Tracking", "strategy|move|announce|plan", "strategy executive research_insights", "m_and_a partnership"),
            S("Geographic Footprint Analysis", "footprint|locations|presence|country|region|expansion", "strategy sales executive", "expansion_geo facility"),
            S("Capacity / Infrastructure Benchmarking", "capacity|plant|facility|fleet|infrastructure|data center", "operations strategy", "facility"),
            S("Partnership & Ecosystem Tracking", "partner|alliance|ecosystem", "strategy technology", "partnership"),
            S("Strategic Initiative Monitoring", "initiative|program|transformation", "strategy executive", ""),
            S("Competitor Strength / Weakness Assessment", "strength|weakness|swot|gap", "strategy marketing sales", ""),
            S("Win / Loss Analysis", "win rate|lost deals|losing|win|loss|churn|renewal", "sales marketing product", "contract_win"),
            S("Competitive Battlecards", "battlecard|sales team|objection|reps|enablement", "sales marketing", "hiring product_launch"),
            S("Competitor Customer Mapping", "customers|accounts|clients|who buys", "sales marketing", "contract_win"),
            S("Competitor Account Penetration Analysis", "account penetration|share of wallet|key accounts", "sales", "contract_win"),
            S("Competitive Positioning Matrix", "positioning|differentiat|rebrand|brand", "marketing strategy", "product_launch"),
            S("Right-to-Win Assessment", "right to win|advantage|moat|differentiat", "strategy executive", "expansion_geo product_launch"),
        ),
    ),
    Pillar(
        id="customer_voc",
        name="Customer & Voice-of-Customer Intelligence",
        purpose="Understand what customers need, how they make decisions, and why they select particular suppliers.",
        pitch="direct evidence from buyers on what they need, how they decide and why they choose one supplier over another",
        assets=("a draft interview guide we would use with their buyers",
                "a short outline of the survey we would run with their target customers"),
        prior=0.04,
        services=(
            S("Customer Surveys", "survey|customers|feedback", "marketing product", ""),
            S("Market Surveys", "survey|market|sample", "marketing strategy research_insights", ""),
            S("Brand & Awareness Studies", "brand|awareness|rebrand|recognition", "marketing", "product_launch"),
            S("Customer Satisfaction Studies", "satisfaction|csat|service|complaint", "marketing operations product", ""),
            S("NPS Studies (Net Promoter Score Study)", "nps|promoter|loyalty|retention", "marketing product", ""),
            S("Pricing Research", "price|pricing|willingness", "product marketing finance", "pricing"),
            S("Purchase Intent Studies", "intent|demand|launch|adoption", "product marketing", "product_launch"),
            S("In-Depth Interviews", "interview|qualitative|buyers", "marketing product strategy", ""),
            S("Focus Group Discussions", "focus group|consumer|concept", "marketing product", "product_launch"),
            S("Expert Interviews", "expert|specialist|kol|physician|engineer", "strategy investment research_insights", "technology regulation"),
            S("Stakeholder Interviews", "stakeholder|partners|distributors", "strategy executive", "partnership"),
            S("Customer Journey Interviews", "journey|onboarding|experience", "marketing product", ""),
            S("Concept / Product Testing", "concept|prototype|test|launch|new product", "product marketing", "product_launch"),
            S("Ethnographic / Observational Research", "observational|ethnograph|in-store|field", "product marketing", ""),
            S("Customer Needs & Pain-Point Analysis", "needs|pain|problem|requirement", "product marketing sales", ""),
            S("Purchase Decision Criteria", "decision criteria|why buyers|select|choose|rfp|tender", "sales marketing", "contract_win"),
            S("Buying-Center Mapping", "buying center|stakeholders|procurement|committee", "sales", ""),
            S("Decision-Making Unit Analysis", "decision-making unit|dmu|approvers", "sales marketing", ""),
            S("Customer Journey Mapping", "journey|funnel|touchpoint", "marketing", ""),
            S("Customer Segmentation", "segment|segmentation|target", "marketing strategy sales", "expansion_geo"),
            S("Persona Development", "persona|ideal customer|icp", "marketing sales", "hiring"),
            S("Switching Behavior", "switch|churn|defect|loyalty|competitor", "marketing sales product", "pricing"),
            S("Unmet Needs Analysis", "unmet|gap|whitespace|need", "product strategy", "product_launch"),
        ),
    ),
    Pillar(
        id="growth_opportunity",
        name="Growth Opportunity Intelligence",
        purpose="Identify where the client should play and which opportunities deserve investment.",
        pitch="a ranked view of which markets, segments and adjacencies deserve their next investment, and why",
        assets=("a one-page outline of how we would screen and rank their growth options",
                "a sample opportunity scoring framework for their sector"),
        prior=0.06,
        services=(
            S("New Market Opportunity Identification", "new market|opportunity|growth", "executive strategy", "funding financial_results"),
            S("Market Entry Assessment", "enter|entry|launch in|expand into|new country|debut", "executive strategy sales", "expansion_geo"),
            S("Geographic Expansion Strategy", "expansion|expand|international|region|country|office|opens", "executive strategy sales", "expansion_geo facility"),
            S("New Customer Segment Identification", "segment|new customers|verticals|industries", "sales marketing strategy", "hiring"),
            S("Adjacent Market Assessment", "adjacent|diversif|new vertical|beyond", "strategy executive", "m_and_a product_launch"),
            S("Product / Service Expansion Opportunities", "new service|new product|extend|portfolio", "product strategy", "product_launch"),
            S("White-Space Analysis", "white space|whitespace|gap|underserved", "strategy product marketing", ""),
            S("Cross-Sell / Upsell Opportunity Assessment", "cross-sell|upsell|existing customers|acquired", "sales marketing", "m_and_a"),
            S("Emerging Opportunity Identification", "emerging|new demand|ai|energy transition|data center", "strategy executive", "technology sustainability"),
            S("Opportunity Screening & Prioritization", "prioriti|screen|options|choose", "strategy executive finance", "funding restructuring"),
            S("Market Attractiveness Assessment", "attractive|profitability|growth rate", "strategy finance investment", ""),
            S("Right-to-Win Analysis", "right to win|advantage|compete", "strategy executive", "expansion_geo"),
        ),
    ),
    Pillar(
        id="gtm_commercial",
        name="Go-to-Market & Commercial Intelligence",
        purpose="Convert market intelligence into actionable commercial opportunities.",
        pitch="a prioritised list of the accounts, segments and channels most likely to convert, and how to reach them",
        assets=("a sample of the account scoring and tiering sheet we would build for them",
                "a short outline of the target account universe we would map for their market"),
        prior=0.05,
        services=(
            S("Go-to-Market Strategy", "go-to-market|gtm|launch|rollout|enter", "executive marketing sales", "product_launch expansion_geo"),
            S("Customer Segment Prioritization", "segment|prioriti|focus|target", "sales marketing", ""),
            S("Target Account Identification", "target accounts|new customers|pipeline|capacity|fill|demand", "sales executive", "facility hiring contract_win"),
            S("Account Universe Development", "account universe|total accounts|list|database", "sales marketing", "hiring expansion_geo"),
            S("Account Scoring & Tiering", "scoring|tiering|prioriti|abm", "sales marketing", "hiring"),
            S("Key Account Intelligence", "key account|strategic account|enterprise customers", "sales", "contract_win"),
            S("Decision-Maker Mapping", "decision maker|who to contact|stakeholder", "sales", "hiring"),
            S("Buying-Center Mapping", "buying center|committee|procurement", "sales", ""),
            S("Sales Trigger Identification", "trigger|signal|timing|intent", "sales marketing", "hiring"),
            S("Channel Strategy", "channel|online|e-commerce|direct|indirect", "sales marketing executive", "expansion_geo"),
            S("Distribution Strategy", "distribution|distributor|dealer|wholesale|retailer", "sales executive operations", "expansion_geo partnership"),
            S("Partner Identification", "partner|reseller|integrator|alliance", "sales executive", "partnership expansion_geo"),
            S("Partner Prioritization", "partner|prioriti", "sales", "partnership"),
            S("Commercial Positioning", "positioning|message|differentiat", "marketing sales", "product_launch"),
            S("Value Proposition Assessment", "value proposition|why buy|message", "marketing product", "product_launch"),
            S("Sales Enablement Intelligence", "sales team|reps|enablement|hiring|sdr|account executive", "sales", "hiring"),
        ),
    ),
    Pillar(
        id="product_portfolio",
        name="Product & Portfolio Strategy",
        purpose="Help clients determine what products, services, or solutions they should develop, prioritize, or reposition.",
        pitch="evidence on which products to build, prioritise, reposition or retire, based on customer demand and competitor gaps",
        assets=("a sample product gap analysis layout for their category",
                "an outline of the launch research we would run before a release"),
        min_scale="small",
        services=(
            S("Product Opportunity Assessment", "opportunity|new product|develop", "product executive", "product_launch"),
            S("Product Portfolio Benchmarking", "portfolio|range|lineup|sku", "product marketing", "product_launch m_and_a"),
            S("Product-Market Fit Assessment", "product-market fit|adoption|traction", "product executive", "product_launch funding"),
            S("Customer Requirement Analysis", "requirement|spec|needs", "product technology", ""),
            S("Feature Prioritization", "feature|roadmap|release", "product technology", "product_launch"),
            S("Product Gap Analysis", "gap|missing|competitor product", "product marketing", "product_launch"),
            S("Portfolio Rationalization", "rationali|discontinue|streamline portfolio|divest|restructur|cost cut", "product executive finance", "restructuring m_and_a"),
            S("New Product Concept Testing", "concept|prototype|new product", "product marketing", "product_launch"),
            S("Pricing & Packaging Research", "packaging|bundle|tier|pricing", "product marketing", "pricing product_launch"),
            S("Product Positioning", "positioning|message", "product marketing", "product_launch"),
            S("Product Launch Research", "launch|unveil|introduce|release", "product marketing", "product_launch"),
            S("Adoption Barrier Assessment", "adoption|barrier|slow uptake", "product marketing", "product_launch technology"),
            S("Product Lifecycle Analysis", "lifecycle|end of life|mature product", "product", ""),
        ),
    ),
    Pillar(
        id="tech_innovation",
        name="Technology & Innovation Intelligence",
        purpose="Help clients understand emerging technologies and their commercial implications.",
        pitch="a practical view of which technologies matter for their business, who the credible vendors are and what adoption will look like",
        assets=("a sample technology vendor map for their use case",
                "a one-page outline of the technology scouting brief we would prepare"),
        min_scale="mid",
        services=(
            S("Emerging Technology Scouting", "emerging|new technology|ai|robotics|quantum", "technology strategy product", "technology"),
            S("Technology Landscape Mapping", "technology|landscape|platform", "technology strategy", "technology"),
            S("Technology Adoption Analysis", "adoption|rollout|deploy|implementation", "technology operations product", "technology"),
            S("Technology Maturity Assessment", "maturity|pilot|proof of concept|readiness", "technology", "technology"),
            S("Technology Roadmaps", "roadmap|plan|strategy", "technology product", ""),
            S("Innovation Benchmarking", "innovation|r&d|patents", "technology strategy", ""),
            S("Patent Landscape Analysis", "patent|ip|intellectual property", "technology legal_compliance", ""),
            S("Startup & Innovator Scouting", "startup|venture|innovator|accelerator", "strategy technology investment", "partnership funding"),
            S("Technology Vendor Mapping", "vendor|supplier|platform|solution provider", "technology procurement operations", "technology"),
            S("Use-Case Identification", "use case|application|pilot", "technology product operations", "technology"),
            S("Adoption Barrier Analysis", "barrier|slow|resistance", "technology product", ""),
            S("Technology Investment Trends", "investment|funding|capex|spend", "technology finance investment", "funding"),
            S("Technology Disruption Assessment", "disrupt|threat|replace", "strategy executive", "technology"),
        ),
    ),
    Pillar(
        id="ecosystem_partnership",
        name="Ecosystem & Partnership Intelligence",
        purpose="Identify the organizations that influence market access and growth.",
        pitch="a vetted map of the partners, distributors, OEMs and integrators that control access to their market, ranked by fit",
        assets=("a sample partner evaluation scorecard",
                "a short outline of the ecosystem map we would build for their target market"),
        services=(
            S("Ecosystem Mapping", "ecosystem|players|stakeholders", "strategy executive", "partnership expansion_geo"),
            S("Supplier Landscape", "supplier|vendor|source", "procurement operations", "supply_chain"),
            S("Distributor / Channel Mapping", "distributor|dealer|channel|reseller", "sales executive", "expansion_geo"),
            S("OEM Mapping", "oem|manufacturer|original equipment", "sales strategy", "contract_win"),
            S("Technology Partner Mapping", "technology partner|integration|platform partner", "technology product", "partnership technology"),
            S("System Integrator Mapping", "integrator|si |implementation partner", "sales technology", "partnership"),
            S("Strategic Partner Identification", "strategic partner|alliance|joint venture|jv", "executive strategy", "partnership expansion_geo"),
            S("Partner Evaluation & Prioritization", "evaluate|prioriti|partner", "strategy sales", "partnership"),
            S("Partnership Opportunity Assessment", "partnership|collaboration|mou|agreement", "strategy executive", "partnership"),
            S("University / Research Institution Mapping", "university|research institute|academic|lab", "technology strategy", "technology"),
            S("Startup Ecosystem Mapping", "startup|venture|accelerator", "strategy technology investment", "funding"),
            S("Industry Association Mapping", "association|trade body|consortium|standards", "legal_compliance marketing", "regulation"),
            S("Stakeholder Influence Mapping", "stakeholder|influence|government|regulator", "legal_compliance strategy", "regulation"),
        ),
    ),
    Pillar(
        id="supply_chain",
        name="Supply Chain & Procurement Intelligence",
        purpose="Improve supply-chain visibility, sourcing decisions, and resilience.",
        pitch="clear visibility of suppliers, input costs, trade flows and supply risk, so sourcing decisions rest on evidence",
        assets=("a short outline of the supplier and cost comparison we would build for them",
                "a sample view of the trade-flow data we would pull for their product category"),
        services=(
            S("Supply Chain Mapping", "supply chain|tier 2|visibility|suppliers", "procurement operations", "supply_chain"),
            S("Supplier Identification", "new supplier|alternative supplier|sourcing|source from", "procurement", "supply_chain tariff_trade"),
            S("Supplier Benchmarking", "supplier|vendor|benchmark", "procurement", "supply_chain"),
            S("Supplier Risk Assessment", "risk|disruption|shortage|single source|insolvency", "procurement operations", "supply_chain restructuring"),
            S("Procurement Benchmarking", "procurement|purchasing|spend", "procurement finance", ""),
            S("Raw Material Analysis", "raw material|resin|steel|aluminum|aluminium|paper|pulp|board|copper|lithium|chemicals|commodity|ink", "procurement operations executive", "supply_chain tariff_trade"),
            S("Cost Structure Analysis", "cost|margin|input cost|inflation", "finance operations executive", "restructuring financial_results"),
            S("Capacity Mapping", "capacity|utilization|plant|output", "operations strategy", "facility"),
            S("Manufacturing Footprint Mapping", "manufacturing|plant|factory|footprint", "operations strategy", "facility"),
            S("Import / Export Analysis", "import|export|customs|shipment|trade", "procurement sales executive", "tariff_trade expansion_geo"),
            S("Trade Flow Analysis", "trade flow|tariff|duties|origin", "procurement strategy", "tariff_trade"),
            S("Supply-Demand Gap Analysis", "shortage|oversupply|gap|demand", "operations strategy", "supply_chain"),
            S("Supply Chain Risk Monitoring", "risk|monitor|disruption|geopolit", "procurement operations", "supply_chain tariff_trade"),
            S("Localization / Nearshoring Assessment", "nearshor|reshor|onshor|localiz|localis|mexico|vietnam|india|tariff", "operations executive procurement", "tariff_trade facility"),
        ),
    ),
    Pillar(
        id="pricing",
        name="Pricing & Commercial Benchmarking",
        purpose="Support pricing, positioning, procurement, and commercial decisions.",
        pitch="competitor price points, customer willingness to pay and price scenarios, so pricing protects margin without losing share",
        assets=("a sample of the price scenarios we would model for them",
                "a sample competitor price architecture view for their category"),
        services=(
            S("Competitor Pricing Benchmarking", "competitor price|price cut|price war|undercut|pricing", "sales marketing finance", "pricing"),
            S("Price Architecture Analysis", "tier|price list|architecture|good-better-best", "product marketing", "product_launch"),
            S("Willingness-to-Pay Research", "willingness|premium|value", "product marketing", "product_launch"),
            S("Price Sensitivity Analysis", "price increase|sensitivity|elastic|pass on|surcharge", "finance sales executive", "pricing tariff_trade"),
            S("Value-Based Pricing Research", "value-based|value|roi", "product marketing sales", ""),
            S("Discount Benchmarking", "discount|rebate|promotion", "sales", "pricing"),
            S("Cost Structure Benchmarking", "cost|margin|cost-to-serve", "finance operations", "restructuring"),
            S("Commercial Model Benchmarking", "commercial model|contract|terms|licensing", "sales executive", "pricing"),
            S("Subscription / Service Model Benchmarking", "subscription|saas|as-a-service|recurring|usage-based", "product executive", "pricing technology"),
            S("Total Cost of Ownership Analysis", "tco|total cost|lifetime cost", "procurement sales product", ""),
            S("Customer Value Perception", "perception|value|worth", "marketing product", ""),
        ),
    ),
    Pillar(
        id="investment_strategic",
        name="Investment & Strategic Intelligence",
        purpose="Support management and investment decisions with evidence-based intelligence.",
        pitch="independent, evidence-based market analysis behind investment and capital allocation decisions",
        assets=("a one-page outline of the market due diligence we would run",
                "a sample investment screening framework for their sector"),
        min_scale="mid",
        services=(
            S("Investment Landscape Analysis", "investment|investors|capital", "investment finance", "funding"),
            S("Market Attractiveness Assessment", "attractive|returns|growth", "investment finance strategy", ""),
            S("Strategic Investment Prioritization", "prioriti|capital allocation|capex|invest", "executive finance strategy", "funding restructuring facility"),
            S("CapEx Trend Analysis", "capex|capital expenditure|spending|investment plan", "finance operations", "facility"),
            S("Investment Flow Tracking", "investment flow|deals|funding rounds", "investment", "funding"),
            S("Business Case Support", "business case|board|approval|justify", "finance strategy executive", "facility funding"),
            S("Commercial Due Diligence", "due diligence|cdd|acquisition|buyout", "investment finance", "m_and_a"),
            S("Market Due Diligence", "due diligence|market check", "investment", "m_and_a funding"),
            S("Target Market Assessment", "target market|market assessment", "investment strategy", ""),
            S("Strategic Scenario Analysis", "scenario|downside|uncertain", "executive finance", "restructuring tariff_trade"),
            S("Risk / Reward Assessment", "risk|reward|return", "finance investment", ""),
            S("Investment Opportunity Screening", "screen|pipeline|opportunities", "investment", "funding"),
        ),
    ),
    Pillar(
        id="m_and_a",
        name="M&A Intelligence",
        purpose="Support acquisition, partnership, and corporate development decisions.",
        pitch="market-grounded analysis for acquisitions: target screening, strategic fit and the post-deal growth case",
        assets=("a sample target screening scorecard",
                "a one-page outline of the post-acquisition market opportunity assessment we would run"),
        min_scale="mid",
        services=(
            S("M&A Landscape Tracking", "m&a|deals|consolidation|acquisitions", "strategy investment", "m_and_a"),
            S("Acquisition Target Identification", "acquisition target|bolt-on|buy-and-build|inorganic", "strategy investment executive", "funding m_and_a"),
            S("Target Screening", "screen|shortlist|targets", "strategy investment", "m_and_a"),
            S("Target Profiling", "profile|target", "strategy investment", "m_and_a"),
            S("Market Due Diligence", "due diligence|market check", "investment strategy", "m_and_a"),
            S("Commercial Due Diligence", "commercial due diligence|cdd", "investment finance", "m_and_a"),
            S("Strategic Fit Assessment", "fit|strategic rationale|integration", "strategy executive", "m_and_a"),
            S("Competitor Acquisition Tracking", "competitor acquires|rival acquisition", "strategy executive", "m_and_a"),
            S("Post-Acquisition Market Opportunity Assessment", "acquired|acquisition completed|integration|combined", "executive strategy sales", "m_and_a"),
            S("Synergy Opportunity Analysis", "synerg|combined|integration", "finance strategy", "m_and_a"),
            S("Cross-Sell Opportunity Assessment", "cross-sell|combined customers|upsell", "sales executive", "m_and_a"),
            S("Market Expansion Potential", "expansion|new markets|reach", "executive strategy", "m_and_a"),
        ),
    ),
    Pillar(
        id="sustainability_esg",
        name="Sustainability & ESG Intelligence",
        purpose="Help clients understand sustainability-driven market shifts and commercial opportunities.",
        pitch="a commercial view of sustainability: which regulations, customer requirements and green demand shifts will affect revenue and cost",
        assets=("a one-page summary of the sustainability requirements we would assess for their customers",
                "a sample competitor sustainability benchmarking grid"),
        services=(
            S("Sustainability Market Trends", "sustainab|green|eco|low-carbon", "sustainability marketing strategy", "sustainability"),
            S("ESG Benchmarking", "esg|rating|disclosure|report", "sustainability finance", "sustainability"),
            S("Regulatory Landscape", "regulation|csrd|cbam|epr|disclosure|mandate|directive", "sustainability legal_compliance", "regulation sustainability"),
            S("Decarbonization Opportunity Assessment", "decarbon|net zero|emissions|carbon|scope 3", "sustainability operations", "sustainability"),
            S("Circular Economy Analysis", "circular|recycl|reuse|refurbish|waste|packaging", "sustainability product operations", "sustainability regulation"),
            S("Energy Efficiency Opportunities", "energy efficiency|energy cost|electricity", "operations sustainability", "sustainability"),
            S("Water & Resource Efficiency", "water|resource efficiency", "operations sustainability", ""),
            S("Sustainable Product Demand", "sustainable product|green demand|eco-friendly|recycled content", "product marketing", "product_launch sustainability"),
            S("Competitor Sustainability Benchmarking", "competitor|benchmark|sustainab", "sustainability marketing", "sustainability"),
            S("Customer Sustainability Requirements", "customer requirement|supplier code|rfp|scope 3", "sales sustainability", "contract_win"),
            S("Green Technology Landscape", "green tech|clean tech|hydrogen|solar|battery|renewable", "technology sustainability", "technology sustainability"),
            S("Sustainable Supply Chain Analysis", "sustainable sourcing|supplier emissions|traceability", "procurement sustainability", "supply_chain sustainability"),
        ),
    ),
    Pillar(
        id="site_selection",
        name="Site Selection & Location Intelligence",
        purpose="Support decisions around where to invest, manufacture, expand, or establish operations.",
        pitch="an objective comparison of candidate locations on demand, talent, cost, logistics, energy and incentives",
        assets=("a sample location scoring model with the criteria we would weight",
                "a one-page outline of the site comparison we would prepare"),
        min_scale="mid",
        services=(
            S("Country / State / City Benchmarking", "country|state|city|location|where to", "operations executive strategy", "facility expansion_geo"),
            S("Demand Hotspot Mapping", "demand|hotspot|customer density", "sales strategy", "expansion_geo"),
            S("Infrastructure Assessment", "infrastructure|port|grid|power|roads", "operations", "facility"),
            S("Talent Availability", "talent|workforce|labor|labour|skills|hiring", "operations hr executive", "facility hiring"),
            S("Supplier Ecosystem Assessment", "supplier ecosystem|cluster|local suppliers", "operations procurement", "facility"),
            S("Logistics Connectivity", "logistics|freight|distribution center|warehouse|port", "operations", "facility"),
            S("Energy / Utility Availability", "energy|power|utility|grid|data center", "operations technology", "facility"),
            S("Regulatory & Incentive Assessment", "incentive|tax credit|subsidy|grant|chips act|ira", "finance operations executive", "facility regulation"),
            S("Competitive Presence", "competitor presence|nearby|cluster", "strategy", "facility"),
            S("Customer Proximity", "customer proximity|near customers|closer to customers", "operations sales", "facility expansion_geo"),
            S("Cost Benchmarking", "cost|wages|rent|land", "finance operations", "facility"),
            S("Location Scoring", "shortlist|compare sites|site selection|new site", "operations executive", "facility"),
        ),
    ),
    Pillar(
        id="consumer_brand",
        name="Consumer & Brand Intelligence",
        purpose="Understand consumers and brand performance for consumer-facing businesses.",
        pitch="clear evidence on how consumers see the brand, how they buy and which messages and concepts will land",
        assets=("a draft consumer survey outline for their category",
                "a sample brand tracking dashboard layout"),
        b2c_only=True,
        services=(
            S("Consumer Behavior Studies", "consumer|shopper|behavio", "marketing product", ""),
            S("Attitude & Usage Studies", "usage|attitude|habits", "marketing product", ""),
            S("Brand Awareness", "awareness|recognition", "marketing", "product_launch"),
            S("Brand Perception", "perception|reputation|image", "marketing", ""),
            S("Brand Tracking", "tracking|brand health|campaign", "marketing", ""),
            S("Consumer Segmentation", "segment|target consumers", "marketing strategy", ""),
            S("Persona Development", "persona|audience", "marketing", ""),
            S("Lifestyle & Generational Studies", "gen z|millennial|generation|lifestyle", "marketing product", ""),
            S("Customer Experience Research", "experience|cx|store|app", "marketing operations", ""),
            S("Concept Testing", "concept|new flavor|new flavour|new range", "product marketing", "product_launch"),
            S("Communication Testing", "campaign|advertising|message|creative", "marketing", "product_launch"),
            S("Purchase Journey Research", "journey|path to purchase|e-commerce|omnichannel", "marketing sales", ""),
            S("Cultural & Behavioral Insights", "culture|cultural|local market", "marketing strategy", "expansion_geo"),
        ),
    ),
    Pillar(
        id="monitoring",
        name="Strategic Monitoring & Intelligence-as-a-Service",
        purpose="Continuous intelligence engagements instead of one-time reports.",
        pitch="an ongoing intelligence feed on competitors, pricing, regulation and market moves, delivered as monthly monitoring and quarterly briefings",
        assets=("a sample one-page monthly competitor monitoring brief format",
                "an outline of what a quarterly executive intelligence briefing would cover for them"),
        min_scale="mid",
        services=(
            S("Monthly Market Monitoring", "market|monthly|ongoing", "strategy research_insights executive", ""),
            S("Competitor Monitoring", "competitor|rival|moves", "strategy marketing sales research_insights", "m_and_a product_launch pricing"),
            S("Technology Monitoring", "technology|ai|innovation", "technology", "technology"),
            S("Pricing Tracking", "price|pricing", "sales finance product", "pricing"),
            S("Regulatory Monitoring", "regulation|policy|compliance|tariff", "legal_compliance sustainability", "regulation tariff_trade"),
            S("Customer / Account Signal Tracking", "account|customer|signals", "sales", "hiring contract_win"),
            S("M&A Tracking", "m&a|acquisition|deal", "strategy investment", "m_and_a"),
            S("Investment Tracking", "investment|funding|capex", "investment finance", "funding"),
            S("Partnership Tracking", "partnership|alliance", "strategy", "partnership"),
            S("Industry News & Development Monitoring", "news|developments|industry", "executive research_insights marketing", "leadership"),
            S("Quarterly Strategic Intelligence Reviews", "quarterly|review|planning", "executive strategy", "leadership financial_results"),
            S("Executive Intelligence Briefings", "briefing|board|leadership|new role|appointed", "executive strategy", "leadership"),
        ),
    ),
)

PILLAR_BY_ID = {p.id: p for p in PILLARS}

# ---------------------------------------------------------------------------
# Fit matrices (0..1). Missing entries count as 0.
# ---------------------------------------------------------------------------

TRIGGER_FIT: dict[str, dict[str, float]] = {
    "expansion_geo": {"growth_opportunity": 1.0, "gtm_commercial": 0.9, "market_intel": 0.75, "ecosystem_partnership": 0.7, "site_selection": 0.55, "competitive_intel": 0.5, "consumer_brand": 0.4, "pricing": 0.3},
    "facility": {"supply_chain": 0.85, "gtm_commercial": 0.8, "site_selection": 0.55, "market_intel": 0.55, "investment_strategic": 0.4, "pricing": 0.35, "sustainability_esg": 0.3},
    "product_launch": {"product_portfolio": 0.9, "pricing": 0.9, "customer_voc": 0.85, "competitive_intel": 0.8, "gtm_commercial": 0.8, "consumer_brand": 0.7},
    "funding": {"growth_opportunity": 0.9, "market_intel": 0.9, "gtm_commercial": 0.8, "competitive_intel": 0.6, "investment_strategic": 0.55, "m_and_a": 0.45},
    "m_and_a": {"m_and_a": 1.0, "gtm_commercial": 0.65, "growth_opportunity": 0.6, "competitive_intel": 0.6, "ecosystem_partnership": 0.4, "customer_voc": 0.35, "product_portfolio": 0.45},
    "partnership": {"ecosystem_partnership": 1.0, "gtm_commercial": 0.7, "competitive_intel": 0.45, "tech_innovation": 0.4},
    "leadership": {"competitive_intel": 0.8, "market_intel": 0.75, "monitoring": 0.7, "growth_opportunity": 0.6, "customer_voc": 0.45},
    "contract_win": {"gtm_commercial": 0.85, "competitive_intel": 0.6, "supply_chain": 0.45, "ecosystem_partnership": 0.4, "market_intel": 0.4},
    "pricing": {"pricing": 1.0, "competitive_intel": 0.8, "customer_voc": 0.6, "monitoring": 0.4},
    "regulation": {"market_intel": 0.8, "monitoring": 0.7, "sustainability_esg": 0.6, "product_portfolio": 0.4, "supply_chain": 0.4, "site_selection": 0.3},
    "tariff_trade": {"supply_chain": 1.0, "pricing": 0.8, "site_selection": 0.65, "market_intel": 0.55, "monitoring": 0.5},
    "supply_chain": {"supply_chain": 1.0, "pricing": 0.5, "ecosystem_partnership": 0.5, "site_selection": 0.45},
    "sustainability": {"sustainability_esg": 1.0, "product_portfolio": 0.5, "customer_voc": 0.45, "supply_chain": 0.5, "competitive_intel": 0.4},
    "technology": {"tech_innovation": 1.0, "competitive_intel": 0.7, "product_portfolio": 0.6, "ecosystem_partnership": 0.5, "customer_voc": 0.4},
    "restructuring": {"investment_strategic": 0.8, "product_portfolio": 0.7, "supply_chain": 0.5, "pricing": 0.5, "competitive_intel": 0.5, "growth_opportunity": 0.4},
    "financial_results": {"growth_opportunity": 0.7, "competitive_intel": 0.7, "market_intel": 0.6, "investment_strategic": 0.55, "pricing": 0.5, "monitoring": 0.4},
    "hiring": {"gtm_commercial": 0.8, "market_intel": 0.5, "competitive_intel": 0.5, "site_selection": 0.35},
    "demand": {"gtm_commercial": 0.7, "customer_voc": 0.6, "market_intel": 0.5},
    "award": {"competitive_intel": 0.3, "customer_voc": 0.3, "consumer_brand": 0.3},
    "event": {"gtm_commercial": 0.35, "competitive_intel": 0.35},
    "general": {"market_intel": 0.3, "competitive_intel": 0.3},
}

PERSONA_FIT: dict[str, dict[str, float]] = {
    "executive": {"growth_opportunity": 1.0, "market_intel": 0.8, "competitive_intel": 0.8, "gtm_commercial": 0.7, "investment_strategic": 0.7, "monitoring": 0.7, "m_and_a": 0.6, "pricing": 0.6, "site_selection": 0.5, "product_portfolio": 0.5, "supply_chain": 0.55, "customer_voc": 0.5, "ecosystem_partnership": 0.5, "tech_innovation": 0.5, "consumer_brand": 0.5, "sustainability_esg": 0.4},
    "strategy": {"market_intel": 1.0, "growth_opportunity": 1.0, "competitive_intel": 0.9, "investment_strategic": 0.9, "m_and_a": 0.9, "monitoring": 0.9, "site_selection": 0.6, "tech_innovation": 0.6, "ecosystem_partnership": 0.6, "gtm_commercial": 0.6, "sustainability_esg": 0.5, "product_portfolio": 0.5, "pricing": 0.5, "customer_voc": 0.5, "consumer_brand": 0.5, "supply_chain": 0.4},
    "marketing": {"customer_voc": 1.0, "consumer_brand": 1.0, "competitive_intel": 0.9, "gtm_commercial": 0.8, "pricing": 0.7, "product_portfolio": 0.7, "market_intel": 0.7, "monitoring": 0.6, "growth_opportunity": 0.6, "ecosystem_partnership": 0.4, "sustainability_esg": 0.3, "tech_innovation": 0.3},
    "sales": {"gtm_commercial": 1.0, "competitive_intel": 0.9, "pricing": 0.8, "customer_voc": 0.7, "ecosystem_partnership": 0.7, "growth_opportunity": 0.6, "monitoring": 0.6, "market_intel": 0.5},
    "product": {"product_portfolio": 1.0, "customer_voc": 0.9, "pricing": 0.8, "competitive_intel": 0.8, "tech_innovation": 0.7, "market_intel": 0.6, "consumer_brand": 0.6, "gtm_commercial": 0.5},
    "procurement": {"supply_chain": 1.0, "pricing": 0.75, "ecosystem_partnership": 0.7, "site_selection": 0.5, "sustainability_esg": 0.5, "monitoring": 0.5, "market_intel": 0.4},
    "operations": {"supply_chain": 0.9, "site_selection": 0.9, "tech_innovation": 0.6, "sustainability_esg": 0.6, "ecosystem_partnership": 0.5, "investment_strategic": 0.4, "pricing": 0.4, "market_intel": 0.4},
    "finance": {"investment_strategic": 1.0, "pricing": 0.8, "m_and_a": 0.8, "market_intel": 0.8, "growth_opportunity": 0.6, "supply_chain": 0.5, "site_selection": 0.5, "monitoring": 0.5, "sustainability_esg": 0.4},
    "investment": {"investment_strategic": 1.0, "m_and_a": 1.0, "market_intel": 0.9, "monitoring": 0.8, "competitive_intel": 0.7, "growth_opportunity": 0.7, "tech_innovation": 0.6},
    "technology": {"tech_innovation": 1.0, "ecosystem_partnership": 0.8, "product_portfolio": 0.6, "competitive_intel": 0.6, "monitoring": 0.6, "market_intel": 0.5, "site_selection": 0.4},
    "sustainability": {"sustainability_esg": 1.0, "supply_chain": 0.6, "market_intel": 0.5, "competitive_intel": 0.5, "customer_voc": 0.5, "tech_innovation": 0.5, "site_selection": 0.4},
    "legal_compliance": {"monitoring": 0.9, "market_intel": 0.8, "sustainability_esg": 0.6, "supply_chain": 0.4, "ecosystem_partnership": 0.4},
    "research_insights": {"monitoring": 1.0, "market_intel": 1.0, "competitive_intel": 1.0, "customer_voc": 0.9, "consumer_brand": 0.8, "tech_innovation": 0.7, "growth_opportunity": 0.7},
    "hr": {"site_selection": 0.5, "competitive_intel": 0.2, "market_intel": 0.2},
    "other": {"market_intel": 0.5, "competitive_intel": 0.5, "growth_opportunity": 0.4, "gtm_commercial": 0.4},
}

# Additive adjustments by industry (-1..+0.3). -1 effectively excludes a pillar.
INDUSTRY_FIT: dict[str, dict[str, float]] = {
    "consumer": {"consumer_brand": 0.3, "customer_voc": 0.1, "pricing": 0.1},
    "manufacturing": {"supply_chain": 0.2, "site_selection": 0.15, "pricing": 0.1, "sustainability_esg": 0.05},
    "packaging_printing": {"supply_chain": 0.25, "pricing": 0.15, "sustainability_esg": 0.15, "gtm_commercial": 0.05},
    "automotive": {"supply_chain": 0.2, "tech_innovation": 0.1, "site_selection": 0.1},
    "chemicals_materials": {"supply_chain": 0.2, "sustainability_esg": 0.15, "pricing": 0.1, "market_intel": 0.05},
    "technology": {"tech_innovation": 0.15, "competitive_intel": 0.1, "gtm_commercial": 0.1, "pricing": 0.05, "supply_chain": -0.2, "site_selection": -0.15},
    "semiconductors_electronics": {"supply_chain": 0.2, "tech_innovation": 0.15, "site_selection": 0.15},
    "telecom": {"tech_innovation": 0.1, "competitive_intel": 0.1, "pricing": 0.1},
    "energy": {"sustainability_esg": 0.2, "tech_innovation": 0.1, "site_selection": 0.1, "market_intel": 0.1},
    "healthcare_life_sciences": {"market_intel": 0.1, "customer_voc": 0.1, "tech_innovation": 0.1, "competitive_intel": 0.05},
    "financial_services": {"competitive_intel": 0.1, "tech_innovation": 0.1, "customer_voc": 0.05, "supply_chain": -0.3, "site_selection": -0.2},
    "logistics": {"supply_chain": 0.2, "site_selection": 0.2, "ecosystem_partnership": 0.1},
    "professional_services": {"gtm_commercial": 0.15, "competitive_intel": 0.1, "supply_chain": -0.35, "site_selection": -0.3, "consumer_brand": -1.0},
    "construction_real_estate": {"site_selection": 0.2, "supply_chain": 0.1, "market_intel": 0.1},
    "agriculture_food": {"supply_chain": 0.2, "sustainability_esg": 0.1, "market_intel": 0.1},
    "mining_metals": {"supply_chain": 0.2, "sustainability_esg": 0.1, "market_intel": 0.1},
    "aerospace_defense": {"supply_chain": 0.15, "tech_innovation": 0.1, "ecosystem_partnership": 0.1},
    "investment_firm": {"investment_strategic": 0.3, "m_and_a": 0.3, "market_intel": 0.1, "supply_chain": -0.4, "site_selection": -0.3},
    "education_public": {"market_intel": 0.05, "supply_chain": -0.3, "pricing": -0.2, "m_and_a": -0.5},
    "unknown": {},
}

SCALE_ORDER = {"small": 0, "mid": 1, "large": 2}

# Pillars that are a stretch for small companies get a penalty instead of a hard block,
# because a "small" read is itself uncertain.
SCALE_PENALTY = {("small", "mid"): 0.25, ("small", "large"): 0.45, ("mid", "large"): 0.2}

# Small companies buy practical, near-term work. Mid and large companies get no adjustment.
SMALL_COMPANY_ADJUST = {"supply_chain": 0.10, "pricing": 0.10, "gtm_commercial": 0.10, "customer_voc": 0.05,
                        "market_intel": -0.05, "competitive_intel": -0.02}
